-- Disable RLS for all core tables to ensure admin panel works with anon key
ALTER TABLE properties DISABLE ROW LEVEL SECURITY;
ALTER TABLE property_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE property_floor_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE property_amenity_relation DISABLE ROW LEVEL SECURITY;
ALTER TABLE nearby_places DISABLE ROW LEVEL SECURITY;
ALTER TABLE agents DISABLE ROW LEVEL SECURITY;
ALTER TABLE amenities DISABLE ROW LEVEL SECURITY;
ALTER TABLE blogs DISABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials DISABLE ROW LEVEL SECURITY;
